### ISSUE TITLE
Is the /tmp folder the best choice for storing the db?

### ISSUE THREAD

**Issue by tsonev7** [nikgraf/graphql-apollo-client-course#3]
Title says it all. Maybe it's better to store the file in the project directory.
Also, I am not sure about Windows users?

By the way, thanks for the course!

**Comment by nikgraf** [comment]
Makes sense if the data directory is listed in .gitignore. Interested to contribute a PR?

**Comment by tsonev7** [comment]
Sure! I will open a PR for the change.
